version: "3.8"
services:
  mysql:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: "app_analytics_user"
      MYSQL_PASSWORD: "app_analytics_pass"
      MYSQL_DATABASE: "app_analytics"
      MYSQL_ROOT_PASSWORD: "MYSQLROOTPASSWORD"
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 10s
      timeout: 20s
      retries: 10
    expose:
      - "3306"
    volumes:
      - app_volume:/var/lib/mysql
  web:
    image: "app-analytics-web"
    environment:
      SSL: "TRUE"
      SERVER_HOST: "0.0.0.0"
      API_HOST: "api"
    ports:
      - "8000:8000"
    depends_on:
      api:
        condition: service_started
  api:
    image: "app-analytics-core"
    expose:
      - "9002"
    environment:
      SERVER_HOST: "0.0.0.0"
      MYSQL_HOST: "mysql"
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  app_volume: {}
      
